# Site settings
title: 爱编
email: gmail for jobinson99
description: "第一种国际化编程语言"
baseurl: ""
url: "http://i-org.ga"

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true

future: true

# 语法高亮
highlighter: pygments

include:
- .nojekyll

# 样式选择
themes: /themes/atlas
